version: "3"

services:
  app:
    build: .
    image: "nestjs:latest"
    entrypoint: ./docker/entrypoint.sh
    container_name: "nestjs_container"
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on: 
      - database

  database:
    image: postgres:13-alpine
    container_name: "postgres_container"
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_DB=development
      - POSTGRES_HOST_AUTH_METHOD=trust
    # volumes:
      # - ./docker/dbdata:/var/lib/postgresql/data
